// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Result is the outcome of an update check.
 */
export class Result {
    "status": Status;
    "currentVersion": string;
    "latestVersion": string;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result($$parsedSource as Partial<Result>);
    }
}

/**
 * Status reports how the running build relates to the latest release.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * StatusAvailable means a newer release exists.
     */
    StatusAvailable = "available",

    /**
     * StatusCurrent means the running build is the latest release.
     */
    StatusCurrent = "current",

    /**
     * StatusAhead means the running build is newer than the latest release.
     */
    StatusAhead = "ahead",
};
