// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AclVersionInfo holds ACL config version information.
 */
export class AclVersionInfo {
    "brokerAddr": string;
    "brokerName": string;
    "clusterName": string;
    "version": string;

    /** Creates a new AclVersionInfo instance. */
    constructor($$source: Partial<AclVersionInfo> = {}) {
        if (!("brokerAddr" in $$source)) {
            this["brokerAddr"] = "";
        }
        if (!("brokerName" in $$source)) {
            this["brokerName"] = "";
        }
        if (!("clusterName" in $$source)) {
            this["clusterName"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AclVersionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AclVersionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AclVersionInfo($$parsedSource as Partial<AclVersionInfo>);
    }
}

/**
 * BrokerNode holds Broker node information.
 */
export class BrokerNode {
    /**
     * Node ID
     */
    "id": number;

    /**
     * Cluster name
     */
    "cluster": string;

    /**
     * Broker name
     */
    "brokerName": string;

    /**
     * Broker ID
     */
    "brokerId": number;

    /**
     * Role (MASTER/SLAVE)
     */
    "role": BrokerRole;

    /**
     * Primary address
     */
    "address": string;

    /**
     * HA address
     */
    "haAddress": string;

    /**
     * Version
     */
    "version": string;

    /**
     * Node status
     */
    "status": NodeStatus;

    /**
     * Topic count
     */
    "topics": number;

    /**
     * Consumer group count
     */
    "groups": number;

    /**
     * Inbound TPS
     */
    "tpsIn": number;

    /**
     * Outbound TPS
     */
    "tpsOut": number;

    /**
     * Unix-second timestamps for TPS history
     */
    "tpsHistoryTimestamps": number[];

    /**
     * Inbound TPS history
     */
    "tpsInHistory": number[];

    /**
     * Outbound TPS history
     */
    "tpsOutHistory": number[];

    /**
     * Messages in today
     */
    "msgInToday": number;

    /**
     * Messages out today
     */
    "msgOutToday": number;

    /**
     * CommitLog disk usage percent
     */
    "commitLogDiskUsage": number;

    /**
     * ConsumeQueue disk usage percent
     */
    "consumeQueueDiskUsage": number;

    /**
     * Last update time
     */
    "lastUpdate": string;

    /**
     * Remark
     */
    "remark": string;

    /** Creates a new BrokerNode instance. */
    constructor($$source: Partial<BrokerNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("brokerName" in $$source)) {
            this["brokerName"] = "";
        }
        if (!("brokerId" in $$source)) {
            this["brokerId"] = 0;
        }
        if (!("role" in $$source)) {
            this["role"] = BrokerRole.$zero;
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("haAddress" in $$source)) {
            this["haAddress"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = NodeStatus.$zero;
        }
        if (!("topics" in $$source)) {
            this["topics"] = 0;
        }
        if (!("groups" in $$source)) {
            this["groups"] = 0;
        }
        if (!("tpsIn" in $$source)) {
            this["tpsIn"] = 0;
        }
        if (!("tpsOut" in $$source)) {
            this["tpsOut"] = 0;
        }
        if (!("tpsHistoryTimestamps" in $$source)) {
            this["tpsHistoryTimestamps"] = [];
        }
        if (!("tpsInHistory" in $$source)) {
            this["tpsInHistory"] = [];
        }
        if (!("tpsOutHistory" in $$source)) {
            this["tpsOutHistory"] = [];
        }
        if (!("msgInToday" in $$source)) {
            this["msgInToday"] = 0;
        }
        if (!("msgOutToday" in $$source)) {
            this["msgOutToday"] = 0;
        }
        if (!("commitLogDiskUsage" in $$source)) {
            this["commitLogDiskUsage"] = 0;
        }
        if (!("consumeQueueDiskUsage" in $$source)) {
            this["consumeQueueDiskUsage"] = 0;
        }
        if (!("lastUpdate" in $$source)) {
            this["lastUpdate"] = "";
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrokerNode instance from a string or object.
     */
    static createFrom($$source: any = {}): BrokerNode {
        const $$createField13_0 = $$createType0;
        const $$createField14_0 = $$createType1;
        const $$createField15_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tpsHistoryTimestamps" in $$parsedSource) {
            $$parsedSource["tpsHistoryTimestamps"] = $$createField13_0($$parsedSource["tpsHistoryTimestamps"]);
        }
        if ("tpsInHistory" in $$parsedSource) {
            $$parsedSource["tpsInHistory"] = $$createField14_0($$parsedSource["tpsInHistory"]);
        }
        if ("tpsOutHistory" in $$parsedSource) {
            $$parsedSource["tpsOutHistory"] = $$createField15_0($$parsedSource["tpsOutHistory"]);
        }
        return new BrokerNode($$parsedSource as Partial<BrokerNode>);
    }
}

/**
 * BrokerRole is the Broker role.
 */
export enum BrokerRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RoleMaster = "MASTER",
    RoleSlave = "SLAVE",
};

/**
 * ClusterInfo holds cluster overview information.
 */
export class ClusterInfo {
    /**
     * Cluster name
     */
    "clusterName": string;

    /**
     * Total Broker count
     */
    "totalBrokers": number;

    /**
     * Online Broker count
     */
    "onlineBrokers": number;

    /**
     * Total Topic count
     */
    "totalTopics": number;

    /**
     * Total consumer group count
     */
    "totalGroups": number;

    /**
     * Average disk usage percent
     */
    "avgDiskUsage": number;

    /**
     * NameServer list
     */
    "nameServers": string[];

    /**
     * Broker list
     */
    "brokers": (BrokerNode | null)[];

    /** Creates a new ClusterInfo instance. */
    constructor($$source: Partial<ClusterInfo> = {}) {
        if (!("clusterName" in $$source)) {
            this["clusterName"] = "";
        }
        if (!("totalBrokers" in $$source)) {
            this["totalBrokers"] = 0;
        }
        if (!("onlineBrokers" in $$source)) {
            this["onlineBrokers"] = 0;
        }
        if (!("totalTopics" in $$source)) {
            this["totalTopics"] = 0;
        }
        if (!("totalGroups" in $$source)) {
            this["totalGroups"] = 0;
        }
        if (!("avgDiskUsage" in $$source)) {
            this["avgDiskUsage"] = 0;
        }
        if (!("nameServers" in $$source)) {
            this["nameServers"] = [];
        }
        if (!("brokers" in $$source)) {
            this["brokers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterInfo {
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nameServers" in $$parsedSource) {
            $$parsedSource["nameServers"] = $$createField6_0($$parsedSource["nameServers"]);
        }
        if ("brokers" in $$parsedSource) {
            $$parsedSource["brokers"] = $$createField7_0($$parsedSource["brokers"]);
        }
        return new ClusterInfo($$parsedSource as Partial<ClusterInfo>);
    }
}

/**
 * ClusterSummary holds cluster status summary for the frontend.
 */
export class ClusterSummary {
    /**
     * Cluster count
     */
    "totalClusters": number;

    /**
     * Total Broker count
     */
    "totalBrokers": number;

    /**
     * Online Broker count
     */
    "onlineBrokers": number;

    /**
     * Warning Broker count
     */
    "warningBrokers": number;

    /**
     * Offline Broker count
     */
    "offlineBrokers": number;

    /**
     * Average disk usage percent
     */
    "avgDiskUsage": number;

    /** Creates a new ClusterSummary instance. */
    constructor($$source: Partial<ClusterSummary> = {}) {
        if (!("totalClusters" in $$source)) {
            this["totalClusters"] = 0;
        }
        if (!("totalBrokers" in $$source)) {
            this["totalBrokers"] = 0;
        }
        if (!("onlineBrokers" in $$source)) {
            this["onlineBrokers"] = 0;
        }
        if (!("warningBrokers" in $$source)) {
            this["warningBrokers"] = 0;
        }
        if (!("offlineBrokers" in $$source)) {
            this["offlineBrokers"] = 0;
        }
        if (!("avgDiskUsage" in $$source)) {
            this["avgDiskUsage"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClusterSummary($$parsedSource as Partial<ClusterSummary>);
    }
}

/**
 * ConnectionStatus is the connection status.
 */
export enum ConnectionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusOnline = "online",
    StatusOffline = "offline",
};

/**
 * ConsumeMode is the consume mode.
 */
export enum ConsumeMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ModeClustering = "CLUSTERING",
    ModeBroadcasting = "BROADCASTING",
};

/**
 * ConsumerGroupItem holds consumer group information.
 */
export class ConsumerGroupItem {
    /**
     * Consumer group ID
     */
    "id": number;

    /**
     * Consumer group name
     */
    "group": string;

    /**
     * Cluster name
     */
    "cluster": string;

    /**
     * Consume mode
     */
    "consumeMode": ConsumeMode;

    /**
     * Status
     */
    "status": GroupStatus;

    /**
     * Online client count
     */
    "onlineClients": number;

    /**
     * Subscribed Topic count
     */
    "topicCount": number;

    /**
     * Message lag
     */
    "lag": number;

    /**
     * Retry QPS
     */
    "retryQps": number;

    /**
     * Dead-letter count
     */
    "dlq": number;

    /**
     * Max retry times
     */
    "maxRetry": number;

    /**
     * Last update time
     */
    "lastUpdate": string;

    /**
     * Remark
     */
    "remark": string;

    /**
     * Subscription list
     */
    "subscriptions": GroupSubscription[];

    /**
     * Client list
     */
    "clients": GroupClient[];

    /** Creates a new ConsumerGroupItem instance. */
    constructor($$source: Partial<ConsumerGroupItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("consumeMode" in $$source)) {
            this["consumeMode"] = ConsumeMode.$zero;
        }
        if (!("status" in $$source)) {
            this["status"] = GroupStatus.$zero;
        }
        if (!("onlineClients" in $$source)) {
            this["onlineClients"] = 0;
        }
        if (!("topicCount" in $$source)) {
            this["topicCount"] = 0;
        }
        if (!("lag" in $$source)) {
            this["lag"] = 0;
        }
        if (!("retryQps" in $$source)) {
            this["retryQps"] = 0;
        }
        if (!("dlq" in $$source)) {
            this["dlq"] = 0;
        }
        if (!("maxRetry" in $$source)) {
            this["maxRetry"] = 0;
        }
        if (!("lastUpdate" in $$source)) {
            this["lastUpdate"] = "";
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("subscriptions" in $$source)) {
            this["subscriptions"] = [];
        }
        if (!("clients" in $$source)) {
            this["clients"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsumerGroupItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ConsumerGroupItem {
        const $$createField13_0 = $$createType7;
        const $$createField14_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subscriptions" in $$parsedSource) {
            $$parsedSource["subscriptions"] = $$createField13_0($$parsedSource["subscriptions"]);
        }
        if ("clients" in $$parsedSource) {
            $$parsedSource["clients"] = $$createField14_0($$parsedSource["clients"]);
        }
        return new ConsumerGroupItem($$parsedSource as Partial<ConsumerGroupItem>);
    }
}

/**
 * GroupClient holds consumer client information.
 */
export class GroupClient {
    /**
     * Client ID
     */
    "clientId": string;

    /**
     * IP address
     */
    "ip": string;

    /**
     * Version
     */
    "version": string;

    /**
     * Last heartbeat time
     */
    "lastHeartbeat": string;

    /** Creates a new GroupClient instance. */
    constructor($$source: Partial<GroupClient> = {}) {
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("lastHeartbeat" in $$source)) {
            this["lastHeartbeat"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupClient instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupClient {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupClient($$parsedSource as Partial<GroupClient>);
    }
}

/**
 * GroupStatus is the consumer group status.
 */
export enum GroupStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    GroupOnline = "online",
    GroupWarning = "warning",
    GroupOffline = "offline",
};

/**
 * GroupSubscription is a subscription relationship.
 */
export class GroupSubscription {
    /**
     * Topic name
     */
    "topic": string;

    /**
     * Filter expression
     */
    "expression": string;

    /**
     * Consume TPS
     */
    "consumeTps": number;

    /** Creates a new GroupSubscription instance. */
    constructor($$source: Partial<GroupSubscription> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("expression" in $$source)) {
            this["expression"] = "";
        }
        if (!("consumeTps" in $$source)) {
            this["consumeTps"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupSubscription instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupSubscription {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupSubscription($$parsedSource as Partial<GroupSubscription>);
    }
}

/**
 * MessageItem holds message information.
 */
export class MessageItem {
    /**
     * Message sequence number
     */
    "id": number;

    /**
     * Cluster name
     */
    "cluster": string;

    /**
     * Topic name
     */
    "topic": string;

    /**
     * Message ID
     */
    "messageId": string;

    /**
     * Message tags
     */
    "tags": string;

    /**
     * Message keys
     */
    "keys": string;

    /**
     * Queue ID
     */
    "queueId": number;

    /**
     * Queue offset
     */
    "queueOffset": number;

    /**
     * Store host
     */
    "storeHost": string;

    /**
     * Born host
     */
    "bornHost": string;

    /**
     * Store time
     */
    "storeTime": string;

    /**
     * Store timestamp
     */
    "storeTimestamp": number;

    /**
     * Message status
     */
    "status": MessageStatus;

    /**
     * Retry times
     */
    "retryTimes": number;

    /**
     * Message body
     */
    "body": string;

    /**
     * Message properties
     */
    "properties": { [_ in string]?: string };

    /** Creates a new MessageItem instance. */
    constructor($$source: Partial<MessageItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = "";
        }
        if (!("keys" in $$source)) {
            this["keys"] = "";
        }
        if (!("queueId" in $$source)) {
            this["queueId"] = 0;
        }
        if (!("queueOffset" in $$source)) {
            this["queueOffset"] = 0;
        }
        if (!("storeHost" in $$source)) {
            this["storeHost"] = "";
        }
        if (!("bornHost" in $$source)) {
            this["bornHost"] = "";
        }
        if (!("storeTime" in $$source)) {
            this["storeTime"] = "";
        }
        if (!("storeTimestamp" in $$source)) {
            this["storeTimestamp"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = MessageStatus.$zero;
        }
        if (!("retryTimes" in $$source)) {
            this["retryTimes"] = 0;
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("properties" in $$source)) {
            this["properties"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageItem instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageItem {
        const $$createField15_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField15_0($$parsedSource["properties"]);
        }
        return new MessageItem($$parsedSource as Partial<MessageItem>);
    }
}

/**
 * MessageStatus is the message status.
 */
export enum MessageStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MsgNormal = "normal",
    MsgRetry = "retry",
    MsgDLQ = "dlq",
};

/**
 * MessageTrackItem holds message track information.
 */
export class MessageTrackItem {
    /**
     * Consumer group
     */
    "consumerGroup": string;

    /**
     * Track type: CONSUMED / NOT_CONSUME_YET / CONSUMED_BUT_FILTERED / UNKNOWN
     */
    "trackType": string;

    /**
     * Consume status description
     */
    "consumeStatus": string;

    /**
     * Exception description
     */
    "exceptionDesc": string;

    /** Creates a new MessageTrackItem instance. */
    constructor($$source: Partial<MessageTrackItem> = {}) {
        if (!("consumerGroup" in $$source)) {
            this["consumerGroup"] = "";
        }
        if (!("trackType" in $$source)) {
            this["trackType"] = "";
        }
        if (!("consumeStatus" in $$source)) {
            this["consumeStatus"] = "";
        }
        if (!("exceptionDesc" in $$source)) {
            this["exceptionDesc"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageTrackItem instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageTrackItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageTrackItem($$parsedSource as Partial<MessageTrackItem>);
    }
}

/**
 * NodeStatus is the node status.
 */
export enum NodeStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NodeOnline = "online",
    NodeWarning = "warning",
    NodeOffline = "offline",
};

/**
 * ResetOffsetRequest is a request to reset offsets.
 */
export class ResetOffsetRequest {
    /**
     * Consumer group name
     */
    "group": string;

    /**
     * Topic name
     */
    "topic": string;

    /**
     * Timestamp (milliseconds)
     */
    "timestamp": number;

    /**
     * Whether to force reset
     */
    "force": boolean;

    /** Creates a new ResetOffsetRequest instance. */
    constructor($$source: Partial<ResetOffsetRequest> = {}) {
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }
        if (!("force" in $$source)) {
            this["force"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResetOffsetRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ResetOffsetRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResetOffsetRequest($$parsedSource as Partial<ResetOffsetRequest>);
    }
}

/**
 * TopicItem holds Topic information.
 */
export class TopicItem {
    /**
     * Topic ID
     */
    "id": number;

    /**
     * Topic name
     */
    "topic": string;

    /**
     * Cluster name
     */
    "cluster": string;

    /**
     * Read queue count
     */
    "readQueue": number;

    /**
     * Write queue count
     */
    "writeQueue": number;

    /**
     * Permission
     */
    "perm": TopicPerm;

    /**
     * Message type
     */
    "messageType": TopicMessageType;

    /**
     * Consumer group count
     */
    "consumerGroups": number;

    /**
     * Inbound TPS
     */
    "tpsIn": number;

    /**
     * Outbound TPS
     */
    "tpsOut": number;

    /**
     * Last update time
     */
    "lastUpdated": string;

    /**
     * Description
     */
    "description": string;

    /**
     * Route information
     */
    "routes": TopicRouteItem[];

    /** Creates a new TopicItem instance. */
    constructor($$source: Partial<TopicItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("readQueue" in $$source)) {
            this["readQueue"] = 0;
        }
        if (!("writeQueue" in $$source)) {
            this["writeQueue"] = 0;
        }
        if (!("perm" in $$source)) {
            this["perm"] = TopicPerm.$zero;
        }
        if (!("messageType" in $$source)) {
            this["messageType"] = TopicMessageType.$zero;
        }
        if (!("consumerGroups" in $$source)) {
            this["consumerGroups"] = 0;
        }
        if (!("tpsIn" in $$source)) {
            this["tpsIn"] = 0;
        }
        if (!("tpsOut" in $$source)) {
            this["tpsOut"] = 0;
        }
        if (!("lastUpdated" in $$source)) {
            this["lastUpdated"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("routes" in $$source)) {
            this["routes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopicItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TopicItem {
        const $$createField12_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("routes" in $$parsedSource) {
            $$parsedSource["routes"] = $$createField12_0($$parsedSource["routes"]);
        }
        return new TopicItem($$parsedSource as Partial<TopicItem>);
    }
}

/**
 * TopicMessageType is the message type.
 */
export enum TopicMessageType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MessageTypeNormal = "Normal",
    MessageTypeFIFO = "FIFO",
    MessageTypeDelay = "Delay",
};

/**
 * TopicPerm is the Topic permission.
 */
export enum TopicPerm {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PermRW = "RW",
    PermR = "R",
    PermW = "W",
    PermDeny = "DENY",
};

/**
 * TopicRouteItem is a Topic route entry.
 */
export class TopicRouteItem {
    /**
     * Broker name
     */
    "broker": string;

    /**
     * Broker address
     */
    "brokerAddr": string;

    /**
     * Read queue count
     */
    "readQueue": number;

    /**
     * Write queue count
     */
    "writeQueue": number;

    /**
     * Permission
     */
    "perm": TopicPerm;

    /** Creates a new TopicRouteItem instance. */
    constructor($$source: Partial<TopicRouteItem> = {}) {
        if (!("broker" in $$source)) {
            this["broker"] = "";
        }
        if (!("brokerAddr" in $$source)) {
            this["brokerAddr"] = "";
        }
        if (!("readQueue" in $$source)) {
            this["readQueue"] = 0;
        }
        if (!("writeQueue" in $$source)) {
            this["writeQueue"] = 0;
        }
        if (!("perm" in $$source)) {
            this["perm"] = TopicPerm.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopicRouteItem instance from a string or object.
     */
    static createFrom($$source: any = {}): TopicRouteItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TopicRouteItem($$parsedSource as Partial<TopicRouteItem>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = BrokerNode.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = GroupSubscription.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = GroupClient.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
const $$createType11 = TopicRouteItem.createFrom;
const $$createType12 = $Create.Array($$createType11);
