// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClusterService exposes cluster topology and health to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * BrokerDetail returns runtime statistics for a single broker.
 */
export function BrokerDetail(brokerAddr: string): $CancellablePromise<model$0.BrokerNode | null> {
    return $Call.ByID(162168797, brokerAddr).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Brokers returns every known broker node.
 */
export function Brokers(): $CancellablePromise<(model$0.BrokerNode | null)[]> {
    return $Call.ByID(848121293).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Info returns the full cluster overview.
 */
export function Info(): $CancellablePromise<model$0.ClusterInfo | null> {
    return $Call.ByID(2635644205).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Summary returns the aggregated cluster counters.
 */
export function Summary(): $CancellablePromise<model$0.ClusterSummary | null> {
    return $Call.ByID(1198823435).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.BrokerNode.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.ClusterInfo.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = model$0.ClusterSummary.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
