// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService exposes RocketMQ connection management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Add stores a new connection and returns it with credentials redacted.
 */
export function Add(input: $models.ConnectionInput): $CancellablePromise<$models.ConnectionView | null> {
    return $Call.ByID(1415602690, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Connect opens the RocketMQ client for a connection.
 */
export function Connect(id: number): $CancellablePromise<void> {
    return $Call.ByID(21390043, id);
}

/**
 * ConnectDefault opens the client for the default connection.
 */
export function ConnectDefault(): $CancellablePromise<void> {
    return $Call.ByID(915621100);
}

/**
 * Disconnect closes the RocketMQ client for a connection.
 */
export function Disconnect(id: number): $CancellablePromise<void> {
    return $Call.ByID(3908522365, id);
}

/**
 * List returns every configured connection with credentials redacted.
 */
export function List(): $CancellablePromise<($models.ConnectionView | null)[]> {
    return $Call.ByID(1791913887).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Remove deletes a connection.
 */
export function Remove(id: number): $CancellablePromise<void> {
    return $Call.ByID(702554075, id);
}

/**
 * SetDefault marks a connection as the default one.
 */
export function SetDefault(id: number): $CancellablePromise<void> {
    return $Call.ByID(2490223430, id);
}

/**
 * Test probes a connection and reports the resulting status.
 */
export function Test(id: number): $CancellablePromise<string> {
    return $Call.ByID(146986595, id);
}

/**
 * Update applies a connection form submission, resolving the credentials mode
 * against the currently stored secrets.
 */
export function Update(id: number, input: $models.ConnectionInput): $CancellablePromise<$models.ConnectionView | null> {
    return $Call.ByID(1062784902, id, input).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ConnectionView.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
