// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConsumerService exposes RocketMQ consumer group operations to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create adds a subscription group on the target broker.
 */
export function Create(input: $models.ConsumerInput): $CancellablePromise<void> {
    return $Call.ByID(2779800763, input);
}

/**
 * Detail returns a single consumer group with its clients and subscriptions.
 */
export function Detail(group: string): $CancellablePromise<model$0.ConsumerGroupItem | null> {
    return $Call.ByID(4111427386, group).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * List returns every consumer group.
 */
export function List(): $CancellablePromise<(model$0.ConsumerGroupItem | null)[]> {
    return $Call.ByID(1407387699).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Remove deletes a subscription group from a broker.
 */
export function Remove(group: string, brokerAddr: string): $CancellablePromise<void> {
    return $Call.ByID(3594458103, group, brokerAddr);
}

/**
 * ResetOffset rewinds a group's consume offset to a timestamp.
 */
export function ResetOffset(request: model$0.ResetOffsetRequest): $CancellablePromise<void> {
    return $Call.ByID(3442632109, request);
}

/**
 * Stats returns the per-queue consume statistics for a group.
 */
export function Stats(group: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3630578774, group).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Update changes the configuration of an existing subscription group.
 */
export function Update(input: $models.ConsumerInput): $CancellablePromise<void> {
    return $Call.ByID(3592571306, input);
}

// Private type creation functions
const $$createType0 = model$0.ConsumerGroupItem.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
