// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * AccessConfigInput carries an ACL access config form submission.
 */
export class AccessConfigInput {
    "accessKey": string;
    "secretKey": string;
    "whiteRemoteAddress": string;
    "isAdmin": boolean;
    "defaultTopicPerm": string;
    "defaultGroupPerm": string;
    "topicPerms": string[];
    "groupPerms": string[];

    /** Creates a new AccessConfigInput instance. */
    constructor($$source: Partial<AccessConfigInput> = {}) {
        if (!("accessKey" in $$source)) {
            this["accessKey"] = "";
        }
        if (!("secretKey" in $$source)) {
            this["secretKey"] = "";
        }
        if (!("whiteRemoteAddress" in $$source)) {
            this["whiteRemoteAddress"] = "";
        }
        if (!("isAdmin" in $$source)) {
            this["isAdmin"] = false;
        }
        if (!("defaultTopicPerm" in $$source)) {
            this["defaultTopicPerm"] = "";
        }
        if (!("defaultGroupPerm" in $$source)) {
            this["defaultGroupPerm"] = "";
        }
        if (!("topicPerms" in $$source)) {
            this["topicPerms"] = [];
        }
        if (!("groupPerms" in $$source)) {
            this["groupPerms"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessConfigInput instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessConfigInput {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("topicPerms" in $$parsedSource) {
            $$parsedSource["topicPerms"] = $$createField6_0($$parsedSource["topicPerms"]);
        }
        if ("groupPerms" in $$parsedSource) {
            $$parsedSource["groupPerms"] = $$createField7_0($$parsedSource["groupPerms"]);
        }
        return new AccessConfigInput($$parsedSource as Partial<AccessConfigInput>);
    }
}

/**
 * ConnectionInput carries a connection form submission.
 */
export class ConnectionInput {
    "name": string;
    "group": string;
    "nameServer": string;
    "timeoutSec": number;
    "enableACL": boolean;
    "accessKey": string;
    "secretKey": string;
    "remark": string;
    "credentialsMode": string;

    /** Creates a new ConnectionInput instance. */
    constructor($$source: Partial<ConnectionInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("nameServer" in $$source)) {
            this["nameServer"] = "";
        }
        if (!("timeoutSec" in $$source)) {
            this["timeoutSec"] = 0;
        }
        if (!("enableACL" in $$source)) {
            this["enableACL"] = false;
        }
        if (!("accessKey" in $$source)) {
            this["accessKey"] = "";
        }
        if (!("secretKey" in $$source)) {
            this["secretKey"] = "";
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("credentialsMode" in $$source)) {
            this["credentialsMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionInput($$parsedSource as Partial<ConnectionInput>);
    }
}

/**
 * ConnectionView is the connection shape sent to the frontend.
 * 
 * AccessKey and SecretKey are always empty: the stored credentials never leave
 * the Go process. The frontend decides what to render from the *Configured
 * flags instead.
 */
export class ConnectionView {
    "id": number;
    "name": string;
    "group": string;
    "nameServer": string;
    "timeoutSec": number;
    "enableACL": boolean;
    "accessKey": string;
    "secretKey": string;
    "accessKeyConfigured": boolean;
    "secretKeyConfigured": boolean;
    "status": model$0.ConnectionStatus;
    "lastCheck": string;
    "isDefault": boolean;
    "remark": string;

    /** Creates a new ConnectionView instance. */
    constructor($$source: Partial<ConnectionView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("nameServer" in $$source)) {
            this["nameServer"] = "";
        }
        if (!("timeoutSec" in $$source)) {
            this["timeoutSec"] = 0;
        }
        if (!("enableACL" in $$source)) {
            this["enableACL"] = false;
        }
        if (!("accessKey" in $$source)) {
            this["accessKey"] = "";
        }
        if (!("secretKey" in $$source)) {
            this["secretKey"] = "";
        }
        if (!("accessKeyConfigured" in $$source)) {
            this["accessKeyConfigured"] = false;
        }
        if (!("secretKeyConfigured" in $$source)) {
            this["secretKeyConfigured"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = model$0.ConnectionStatus.$zero;
        }
        if (!("lastCheck" in $$source)) {
            this["lastCheck"] = "";
        }
        if (!("isDefault" in $$source)) {
            this["isDefault"] = false;
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionView instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionView($$parsedSource as Partial<ConnectionView>);
    }
}

/**
 * ConsumerInput carries a consumer group form submission.
 */
export class ConsumerInput {
    "group": string;
    "brokerAddr": string;
    "consumeMode": string;
    "maxRetry": number;

    /** Creates a new ConsumerInput instance. */
    constructor($$source: Partial<ConsumerInput> = {}) {
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("brokerAddr" in $$source)) {
            this["brokerAddr"] = "";
        }
        if (!("consumeMode" in $$source)) {
            this["consumeMode"] = "";
        }
        if (!("maxRetry" in $$source)) {
            this["maxRetry"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsumerInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ConsumerInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConsumerInput($$parsedSource as Partial<ConsumerInput>);
    }
}

/**
 * DeleteInput identifies a message to skip via ConsumeMessageDirectly.
 */
export class DeleteInput {
    "topic": string;
    "messageId": string;
    "consumerGroup": string;
    "storeHost": string;

    /** Creates a new DeleteInput instance. */
    constructor($$source: Partial<DeleteInput> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("consumerGroup" in $$source)) {
            this["consumerGroup"] = "";
        }
        if (!("storeHost" in $$source)) {
            this["storeHost"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteInput($$parsedSource as Partial<DeleteInput>);
    }
}

/**
 * MessageQuery carries the message search form.
 */
export class MessageQuery {
    "topic": string;
    "key": string;
    "tag": string;
    "maxResults": number;
    "startTime": number;
    "endTime": number;

    /** Creates a new MessageQuery instance. */
    constructor($$source: Partial<MessageQuery> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("maxResults" in $$source)) {
            this["maxResults"] = 0;
        }
        if (!("startTime" in $$source)) {
            this["startTime"] = 0;
        }
        if (!("endTime" in $$source)) {
            this["endTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageQuery($$parsedSource as Partial<MessageQuery>);
    }
}

/**
 * ResendInput identifies a message to push back to a consumer group.
 */
export class ResendInput {
    "consumerGroup": string;
    "clientId": string;
    "topic": string;
    "messageId": string;

    /** Creates a new ResendInput instance. */
    constructor($$source: Partial<ResendInput> = {}) {
        if (!("consumerGroup" in $$source)) {
            this["consumerGroup"] = "";
        }
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResendInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ResendInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResendInput($$parsedSource as Partial<ResendInput>);
    }
}

/**
 * SendInput carries a produced message.
 */
export class SendInput {
    "topic": string;
    "tags": string;
    "keys": string;
    "body": string;
    "delayLevel": number;

    /** Creates a new SendInput instance. */
    constructor($$source: Partial<SendInput> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = "";
        }
        if (!("keys" in $$source)) {
            this["keys"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("delayLevel" in $$source)) {
            this["delayLevel"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SendInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SendInput($$parsedSource as Partial<SendInput>);
    }
}

/**
 * SettingsInput carries a settings form submission.
 */
export class SettingsInput {
    /**
     * General
     * Theme: "system" | "light" | "dark"
     */
    "theme": string;

    /**
     * Language: "en" | "zh"
     */
    "language": string;

    /**
     * Font size (px): 12-18
     */
    "fontSize": number;

    /**
     * UI font
     */
    "uiFont": string;

    /**
     * Monospace font
     */
    "monospaceFont": string;

    /**
     * Auto-connect to last cluster on startup
     */
    "autoConnectLast": boolean;

    /**
     * Check GitHub for a newer release in the background
     */
    "autoCheckUpdate": boolean;

    /**
     * Close behaviour: "minimizeToTray" | "quit"
     */
    "closeBehavior": string;

    /**
     * Connection and network
     * Connect timeout (ms)
     */
    "connectTimeoutMs": number;

    /**
     * Request timeout (ms)
     */
    "requestTimeoutMs": number;

    /**
     * Default AccessKey
     */
    "globalAccessKey": string;

    /**
     * Default SecretKey
     */
    "globalSecretKey": string;

    /**
     * Skip TLS verification
     */
    "skipTlsVerify": boolean;

    /**
     * Enable proxy
     */
    "proxyEnabled": boolean;

    /**
     * Proxy type: "http" | "socks5"
     */
    "proxyType": string;

    /**
     * Proxy host
     */
    "proxyHost": string;

    /**
     * Proxy port
     */
    "proxyPort": string;

    /**
     * Monitoring and alerts
     * Consumer lag alert threshold (0=disabled)
     */
    "lagAlertThreshold": number;

    /**
     * CommitLog disk alert threshold percent (0=disabled)
     */
    "diskAlertThreshold": number;

    /**
     * System notification on new alerts
     */
    "desktopNotifications": boolean;

    /**
     * Messages and display
     * Timezone: "local" | "utc"
     */
    "timezone": string;

    /**
     * Timestamp format: "datetime" | "ms"
     */
    "timestampFormat": string;

    /**
     * Auto-format JSON
     */
    "autoFormatJson": boolean;

    /**
     * Message truncation threshold (bytes)
     */
    "maxPayloadRenderBytes": number;

    /**
     * Page fetch size
     */
    "fetchLimit": number;
    "globalCredentialsMode": string;

    /** Creates a new SettingsInput instance. */
    constructor($$source: Partial<SettingsInput> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("fontSize" in $$source)) {
            this["fontSize"] = 0;
        }
        if (!("uiFont" in $$source)) {
            this["uiFont"] = "";
        }
        if (!("monospaceFont" in $$source)) {
            this["monospaceFont"] = "";
        }
        if (!("autoConnectLast" in $$source)) {
            this["autoConnectLast"] = false;
        }
        if (!("autoCheckUpdate" in $$source)) {
            this["autoCheckUpdate"] = false;
        }
        if (!("closeBehavior" in $$source)) {
            this["closeBehavior"] = "";
        }
        if (!("connectTimeoutMs" in $$source)) {
            this["connectTimeoutMs"] = 0;
        }
        if (!("requestTimeoutMs" in $$source)) {
            this["requestTimeoutMs"] = 0;
        }
        if (!("globalAccessKey" in $$source)) {
            this["globalAccessKey"] = "";
        }
        if (!("globalSecretKey" in $$source)) {
            this["globalSecretKey"] = "";
        }
        if (!("skipTlsVerify" in $$source)) {
            this["skipTlsVerify"] = false;
        }
        if (!("proxyEnabled" in $$source)) {
            this["proxyEnabled"] = false;
        }
        if (!("proxyType" in $$source)) {
            this["proxyType"] = "";
        }
        if (!("proxyHost" in $$source)) {
            this["proxyHost"] = "";
        }
        if (!("proxyPort" in $$source)) {
            this["proxyPort"] = "";
        }
        if (!("lagAlertThreshold" in $$source)) {
            this["lagAlertThreshold"] = 0;
        }
        if (!("diskAlertThreshold" in $$source)) {
            this["diskAlertThreshold"] = 0;
        }
        if (!("desktopNotifications" in $$source)) {
            this["desktopNotifications"] = false;
        }
        if (!("timezone" in $$source)) {
            this["timezone"] = "";
        }
        if (!("timestampFormat" in $$source)) {
            this["timestampFormat"] = "";
        }
        if (!("autoFormatJson" in $$source)) {
            this["autoFormatJson"] = false;
        }
        if (!("maxPayloadRenderBytes" in $$source)) {
            this["maxPayloadRenderBytes"] = 0;
        }
        if (!("fetchLimit" in $$source)) {
            this["fetchLimit"] = 0;
        }
        if (!("globalCredentialsMode" in $$source)) {
            this["globalCredentialsMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsInput($$parsedSource as Partial<SettingsInput>);
    }
}

/**
 * SettingsView is the settings shape sent to the frontend, with the global ACL
 * credentials replaced by whether they are configured.
 */
export class SettingsView {
    /**
     * General
     * Theme: "system" | "light" | "dark"
     */
    "theme": string;

    /**
     * Language: "en" | "zh"
     */
    "language": string;

    /**
     * Font size (px): 12-18
     */
    "fontSize": number;

    /**
     * UI font
     */
    "uiFont": string;

    /**
     * Monospace font
     */
    "monospaceFont": string;

    /**
     * Auto-connect to last cluster on startup
     */
    "autoConnectLast": boolean;

    /**
     * Check GitHub for a newer release in the background
     */
    "autoCheckUpdate": boolean;

    /**
     * Close behaviour: "minimizeToTray" | "quit"
     */
    "closeBehavior": string;

    /**
     * Connection and network
     * Connect timeout (ms)
     */
    "connectTimeoutMs": number;

    /**
     * Request timeout (ms)
     */
    "requestTimeoutMs": number;

    /**
     * Default AccessKey
     */
    "globalAccessKey": string;

    /**
     * Default SecretKey
     */
    "globalSecretKey": string;

    /**
     * Skip TLS verification
     */
    "skipTlsVerify": boolean;

    /**
     * Enable proxy
     */
    "proxyEnabled": boolean;

    /**
     * Proxy type: "http" | "socks5"
     */
    "proxyType": string;

    /**
     * Proxy host
     */
    "proxyHost": string;

    /**
     * Proxy port
     */
    "proxyPort": string;

    /**
     * Monitoring and alerts
     * Consumer lag alert threshold (0=disabled)
     */
    "lagAlertThreshold": number;

    /**
     * CommitLog disk alert threshold percent (0=disabled)
     */
    "diskAlertThreshold": number;

    /**
     * System notification on new alerts
     */
    "desktopNotifications": boolean;

    /**
     * Messages and display
     * Timezone: "local" | "utc"
     */
    "timezone": string;

    /**
     * Timestamp format: "datetime" | "ms"
     */
    "timestampFormat": string;

    /**
     * Auto-format JSON
     */
    "autoFormatJson": boolean;

    /**
     * Message truncation threshold (bytes)
     */
    "maxPayloadRenderBytes": number;

    /**
     * Page fetch size
     */
    "fetchLimit": number;
    "globalAccessKeyConfigured": boolean;
    "globalSecretKeyConfigured": boolean;

    /** Creates a new SettingsView instance. */
    constructor($$source: Partial<SettingsView> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("fontSize" in $$source)) {
            this["fontSize"] = 0;
        }
        if (!("uiFont" in $$source)) {
            this["uiFont"] = "";
        }
        if (!("monospaceFont" in $$source)) {
            this["monospaceFont"] = "";
        }
        if (!("autoConnectLast" in $$source)) {
            this["autoConnectLast"] = false;
        }
        if (!("autoCheckUpdate" in $$source)) {
            this["autoCheckUpdate"] = false;
        }
        if (!("closeBehavior" in $$source)) {
            this["closeBehavior"] = "";
        }
        if (!("connectTimeoutMs" in $$source)) {
            this["connectTimeoutMs"] = 0;
        }
        if (!("requestTimeoutMs" in $$source)) {
            this["requestTimeoutMs"] = 0;
        }
        if (!("globalAccessKey" in $$source)) {
            this["globalAccessKey"] = "";
        }
        if (!("globalSecretKey" in $$source)) {
            this["globalSecretKey"] = "";
        }
        if (!("skipTlsVerify" in $$source)) {
            this["skipTlsVerify"] = false;
        }
        if (!("proxyEnabled" in $$source)) {
            this["proxyEnabled"] = false;
        }
        if (!("proxyType" in $$source)) {
            this["proxyType"] = "";
        }
        if (!("proxyHost" in $$source)) {
            this["proxyHost"] = "";
        }
        if (!("proxyPort" in $$source)) {
            this["proxyPort"] = "";
        }
        if (!("lagAlertThreshold" in $$source)) {
            this["lagAlertThreshold"] = 0;
        }
        if (!("diskAlertThreshold" in $$source)) {
            this["diskAlertThreshold"] = 0;
        }
        if (!("desktopNotifications" in $$source)) {
            this["desktopNotifications"] = false;
        }
        if (!("timezone" in $$source)) {
            this["timezone"] = "";
        }
        if (!("timestampFormat" in $$source)) {
            this["timestampFormat"] = "";
        }
        if (!("autoFormatJson" in $$source)) {
            this["autoFormatJson"] = false;
        }
        if (!("maxPayloadRenderBytes" in $$source)) {
            this["maxPayloadRenderBytes"] = 0;
        }
        if (!("fetchLimit" in $$source)) {
            this["fetchLimit"] = 0;
        }
        if (!("globalAccessKeyConfigured" in $$source)) {
            this["globalAccessKeyConfigured"] = false;
        }
        if (!("globalSecretKeyConfigured" in $$source)) {
            this["globalSecretKeyConfigured"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsView instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsView($$parsedSource as Partial<SettingsView>);
    }
}

/**
 * TopicInput carries a topic form submission.
 */
export class TopicInput {
    "topic": string;
    "brokerAddr": string;
    "readQueue": number;
    "writeQueue": number;
    "perm": string;

    /** Creates a new TopicInput instance. */
    constructor($$source: Partial<TopicInput> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("brokerAddr" in $$source)) {
            this["brokerAddr"] = "";
        }
        if (!("readQueue" in $$source)) {
            this["readQueue"] = 0;
        }
        if (!("writeQueue" in $$source)) {
            this["writeQueue"] = 0;
        }
        if (!("perm" in $$source)) {
            this["perm"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopicInput instance from a string or object.
     */
    static createFrom($$source: any = {}): TopicInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TopicInput($$parsedSource as Partial<TopicInput>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
