// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes application settings to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearCache drops cached broker and topic metadata.
 */
export function ClearCache(): $CancellablePromise<void> {
    return $Call.ByID(741059075);
}

/**
 * Get returns the current settings with credentials redacted.
 */
export function Get(): $CancellablePromise<$models.SettingsView | null> {
    return $Call.ByID(2363841514).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Reset restores the default settings.
 */
export function Reset(): $CancellablePromise<$models.SettingsView | null> {
    return $Call.ByID(2582353713).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Update applies a settings form submission, resolving the global credentials
 * mode against the currently stored secrets.
 */
export function Update(input: $models.SettingsInput): $CancellablePromise<$models.SettingsView | null> {
    return $Call.ByID(1071617479, input).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SettingsView.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
