// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService exposes application-level operations that need the desktop
 * shell: version reporting, update checks, external links and file dialogs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../update/models.js";

/**
 * CheckUpdate compares the running build against the latest GitHub release.
 */
export function CheckUpdate(): $CancellablePromise<update$0.Result> {
    return $Call.ByID(2028650955).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ExportConfig prompts for a destination and writes the full configuration.
 * It returns the written path, or an empty string when the user cancels.
 */
export function ExportConfig(): $CancellablePromise<string> {
    return $Call.ByID(2019596734);
}

/**
 * ImportConfig prompts for a config file and applies it. It returns the source
 * path, or an empty string when the user cancels.
 */
export function ImportConfig(): $CancellablePromise<string> {
    return $Call.ByID(1441168317);
}

/**
 * OpenExternal opens an allow-listed HTTPS URL in the user's browser.
 */
export function OpenExternal(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(4127192401, rawURL);
}

/**
 * Version returns the running application version.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(3245681566);
}

// Private type creation functions
const $$createType0 = update$0.Result.createFrom;
