// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService keeps the native window chrome in step with the renderer theme.
 * 
 * Everything else about the window - minimise, maximise, close - is driven from
 * the frontend through the Wails window runtime and needs no binding here.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * SetAppearance applies the light or dark window background colour.
 */
export function SetAppearance(dark: boolean): $CancellablePromise<void> {
    return $Call.ByID(1754102795, dark);
}
